name: Estimation Tool Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          backend
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
    - name: Run backend tests
      working-directory: ./backend
      run: npm run test
    - name: Lint backend
      working-directory: ./backend
      run: npm run lint
    - name: Build backend
      working-directory: ./backend
      run: npm run build
  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          frontend
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm run test:ci
    - name: Lint frontend
      working-directory: ./frontend
      run: npm run lint
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
  
